# Site settings
title: Pedro Santana - Software Engineer
description: Pedro Santana's personal portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "pedrosantana.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pedro Santana
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Engineer Student
email: pedroems.147@gmail.com
# twitter_username: lorem_ipsum
github_username:  Pedro-Emanuel
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
